# Generated by Django 5.1.3 on 2025-01-21 07:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='image/upload/v1737444623/default-user-icon-13_ez6cy7.png', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
