# Generated by Django 5.1.3 on 2025-01-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigIntegerField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
