# Generated by Django 5.1.3 on 2025-01-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
