# Generated by Django 5.1.3 on 2025-01-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_id'),
        ('recipe', '0005_recipe_is_declined'),
    ]

    operations = [
    ]
