# Generated by Django 5.1.3 on 2024-12-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_dishes',
            field=models.ManyToManyField(blank=True, related_name='author_by', to='recipe.recipe'),
        ),
    ]
